# Welcome to Serverless!

# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  timeout: 30 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL # points to file containing the function logic
    events: # specifies events that will trigger the function code
       - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken # points to file containing the function logic
    events: # specifies events that will trigger the function code
        - http:
            path: api/token/{code}
            method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents # points to file containing the function logic
    events: # specifies events that will trigger the function code
        - http:
            path: api/get-events/{access_token}
            method: get
